---
version: '3'
services:
  ####################
  ##                ##
  ## Kafka Cluster  ##
  ##   1 ZK + 3 KB  ##
  ##                ##
  ####################
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.port=5555'
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_tx_logs:/var/lib/zookeeper/log
  kafka-0:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka_data0:/var/lib/kafka/data
  kafka-1:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka_data1:/var/lib/kafka/data
  kafka-2:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka_data2:/var/lib/kafka/data
  ###################
  ##               ##
  ## JMX Exporters ##
  ##               ##
  ###################
  zookeeper-jmx-exporter:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./zookeeper-jmx-exporter/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7556:7556
    environment:
      JMX_EXPORTER_HTTP_PORT: 7556
  kafka-jmx-exporter-0:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./kafka-jmx-exporter-0/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7557:7557
    environment:
      JMX_EXPORTER_HTTP_PORT: 7557
  kafka-jmx-exporter-1:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./kafka-jmx-exporter-1/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7558:7558
    environment:
      JMX_EXPORTER_HTTP_PORT: 7558
  kafka-jmx-exporter-2:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./kafka-jmx-exporter-2/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7559:7559
    environment:
      JMX_EXPORTER_HTTP_PORT: 7559
  #################
  ##             ##
  ## Monitoring  ##
  ##             ##
  #################
  prometheus:
    image: prom/prometheus:v2.3.2
    ports:
      - 9090:9090
    volumes:
      - prom_data:/prometheus
      - ./prom-config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:5.2.2
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - grafana_data:/var/lib/grafana 
  
volumes:
  zk_data:
  zk_tx_logs:
  kafka_data0:
  kafka_data1:
  kafka_data2:
  prom_data:
  grafana_data:
networks:
  default:
    external:
      name: composes
